services:
  flexit-analytics:
    platform: windows/amd64
    container_name: flexit-analytics
    networks:
      - flexit-network
    build:
      context: .
      dockerfile: Dockerfile.flexit
    image: ghcr.io/flexanalytics/flexit-windows:${FLEXIT_VERSION}
    pull_policy: missing
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@flexit-content-database:5432/${DB_NAME}
    ports:
      - "${FLEXIT_PORT}:3030"
    volumes:
      - "flexit_config:C:/FlexIt/config"
      - "flexit_datasets:C:/FlexIt/datasets"
      - "flexit_deployments:C:/FlexIt/deployments"
      - "flexit_logs:C:/FlexIt/logs"
      - "flexit_webcontent:C:/FlexIt/webcontent"

volumes:
  flexit_config:
    name: flexit_config
  flexit_datasets:
    name: flexit_datasets
  flexit_deployments:
    name: flexit_deployments
  flexit_logs:
    name: flexit_logs
  flexit_webcontent:
    name: flexit_webcontent

networks:
  flexit-network:
    name: flexit-network
    driver: nat
